using api.DTOs.Auth;
using api.DTOs.User;
using api.Interfaces;
using api.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace api.Controllers
{
    [Route("api/auth")]
    [ApiController]
    public class AuthController : ControllerBase
    {
        private readonly UserManager<AppUser> _userManager;
        private readonly ITokenService _tokenService;

        public AuthController(UserManager<AppUser> userManager, ITokenService tokenService)
        {
            _userManager = userManager;
            _tokenService = tokenService;
        }

        [HttpPost("register")]
        public async Task<ActionResult<AuthResDto>> Register([FromBody] RegisterReqDto request)
        {
    
            if (!ModelState.IsValid)
                return BadRequest(ModelState);

            //Check if email already exists BEFORE creating user
            //Identity's CreateAsync will fail if email exists, but this gives a cleaner error message without hitting the database for a full insert.
            var existingUser = await _userManager.FindByEmailAsync(request.Email);
            if (existingUser != null)
            {
                return Conflict(new { message = "An account already exists with this email." });
            }

            var appUser = new AppUser
            {
                UserName = request.Email,
                Email = request.Email,
                DisplayName = request.DisplayName,
                CreatedAt = DateTime.UtcNow,
                EmailConfirmed = true
            };

            var createResult = await _userManager.CreateAsync(appUser, request.Password);

            if (!createResult.Succeeded)
            {
                //Map Identity errors to a single string. Flutter expects:
                //{ "message": "something readable" }
                var errorMessage = string.Join("; ", createResult.Errors.Select(e => e.Description));
                return BadRequest(new { message = errorMessage });
            }

            var roleResult = await _userManager.AddToRoleAsync(appUser, "User");

            if (!roleResult.Succeeded)
            {
                // WHY: If role assignment fails, the user exists but has no role.
                // Log this for admin review — don't expose internal details to client.
                var errorMessage = string.Join("; ", roleResult.Errors.Select(e => e.Description));
                return StatusCode(500, new { message = "User created but role assignment failed." });
            }

            var token = _tokenService.CreateToken(appUser);

            var response = new AuthResDto
            {
                Token = token,
                //Refresh tokens should be generated by the service, not hardcoded.
                RefreshToken = null,
                ExpiresAt = _tokenService.GetTokenExpiry(), //ask the service
                User = new UserDto
                {
                    Id = appUser.Id,
                    Email = appUser.Email!,
                    DisplayName = appUser.DisplayName,
                    Roles = new List<string> { "User" },
                    CreatedAt = appUser.CreatedAt
                }
            };

            return Ok(response);
        }

        [HttpPost("login")]
        public async Task<ActionResult<AuthResDto>> Login([FromBody] LoginReqDto request)
        {
            if (!ModelState.IsValid)
                return BadRequest(ModelState);

            //FindByEmailAsync normalizes the email internally.
            //"Test@Email.COM" becomes "TEST@EMAIL.COM" in the database lookup.
            var user = await _userManager.FindByEmailAsync(request.Email);

            if (user == null)
                return Unauthorized(new { message = "Invalid email or password." });

            //CheckPasswordAsync hashes the provided password with PBKDF2
            //and compares against the stored hash. Never compare strings directly.
            var isPasswordValid = await _userManager.CheckPasswordAsync(user, request.Password);

            if (!isPasswordValid)
            {
                //Record the failed attempt. After 5 failures (configurable),
                //LockoutEnd will be set and the account is locked.
                await _userManager.AccessFailedAsync(user);
                return Unauthorized(new { message = "Invalid email or password." });
            }

            //Reset the counter on success. Otherwise the user might get
            //locked out from one mistake hours ago.
            await _userManager.ResetAccessFailedCountAsync(user);

            var token = _tokenService.CreateToken(user);
            var roles = await _userManager.GetRolesAsync(user);

            return Ok(new AuthResDto
            {
                Token = token,
                RefreshToken = null,
                ExpiresAt = _tokenService.GetTokenExpiry(),
                User = new UserDto
                {
                    Id = user.Id,
                    Email = user.Email!,
                    DisplayName = user.DisplayName,
                    Roles = roles.ToList(),
                    CreatedAt = user.CreatedAt
                }
            });
        }
    }
}