using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace api.Models
{
    public class User
    {
        // Primary key with auto-increment
        [Key]
        // This attribute indicates that the Id property is the primary key of the User table
        // and that its value will be generated by the database when a new User is inserted.
       // [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        [Required] // Cannot be null
        [MaxLength(255)] // VARCHAR(255)
        [EmailAddress] // Validates email format
        public string Email { get; set; } = string.Empty;
        [Required]
        public string PasswordHash { get; set; } = string.Empty;       
         public string? DisplayName { get; set; }
       
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
        
        // Navigation property
        // This allows us to access the products associated with this user
        public List<Product> Products { get; set; } = new List<Product>();
    }
}