// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVOmeGRe_DkITQpU0TqReFmFspZEOMeV8',
    appId: '1:593594404324:web:744cd2101261d3a5f1cbf1',
    messagingSenderId: '593594404324',
    projectId: 'bsm-scanner',
    authDomain: 'bsm-scanner.firebaseapp.com',
    storageBucket: 'bsm-scanner.firebasestorage.app',
    measurementId: 'G-EYRJHV49T6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuGO1V3tGjYliS_6VxNhWmshqx1bO78po',
    appId: '1:593594404324:android:5593d282db4dd5e5f1cbf1',
    messagingSenderId: '593594404324',
    projectId: 'bsm-scanner',
    storageBucket: 'bsm-scanner.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7UvQnrCdUJz8VrbYVufYcXOFy8iWcmDE',
    appId: '1:593594404324:ios:16b4d6bae4152caff1cbf1',
    messagingSenderId: '593594404324',
    projectId: 'bsm-scanner',
    storageBucket: 'bsm-scanner.firebasestorage.app',
    iosBundleId: 'com.example.bsmScannerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7UvQnrCdUJz8VrbYVufYcXOFy8iWcmDE',
    appId: '1:593594404324:ios:16b4d6bae4152caff1cbf1',
    messagingSenderId: '593594404324',
    projectId: 'bsm-scanner',
    storageBucket: 'bsm-scanner.firebasestorage.app',
    iosBundleId: 'com.example.bsmScannerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVOmeGRe_DkITQpU0TqReFmFspZEOMeV8',
    appId: '1:593594404324:web:f54c526f9ca28bd6f1cbf1',
    messagingSenderId: '593594404324',
    projectId: 'bsm-scanner',
    authDomain: 'bsm-scanner.firebaseapp.com',
    storageBucket: 'bsm-scanner.firebasestorage.app',
    measurementId: 'G-DKSN5KLKRL',
  );
}
